name: fanfiction-nlp
dependencies:
  - python=3.8.8
  - scipy=1.6.2
  - pandas=1.2.3
  - scikit-learn=0.24.1
  - nltk=3.5
  - spacy=2.3.5
  - inflect=5.3.0
  - pytorch=1.7.1
  - pip=21.0.1
  - pip:
    - benepar==0.2.0
    - protobuf==3.20.1
    - pyhocon==0.3.57
    - transformers==4.4.2
